version: '3'

services:
  server:
    image: cconsuelo/web-socketer
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - web-socketer:/data/db
    ports:
      - '27017:27017'

volumes:
  web-socketer:
